---
# You must replace the YNAB_API_TOKEN value below!
version: "3"
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
    - grafana_data:/var/lib/grafana
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
    - prometheus_data:/prometheus
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/usr/share/prometheus/console_libraries
    - --web.console.templates=/usr/share/prometheus/consoles
  ynab-exporter:
    image: mcbobke/ynab-exporter:latest
    container_name: ynab-exporter
    environment:
      YNAB_API_TOKEN: "{{ ynab_api_token }}"
      PORT: "9090"
      BIND_ADDR: "0.0.0.0"
volumes:
  grafana_data:
  prometheus_data:
