---
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
- job_name: ynab-exporter
  static_configs:
  - targets:
    - "ynab-exporter:9090"
  scrape_interval: 2m
