name: Binary - Build/Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: [1.17.4]
      fail-fast: true
    steps:
      - name: Checkout tag
        uses: actions/checkout@v2.4.0
      
      - name: Setup go 1.17.4
        uses: actions/setup-go@v2.1.5
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Build ynab-exporter
        shell: bash
        run: >-
          BUILD_VERSION=${GITHUB_REF_NAME}
          BUILD_TIME=$(date +%s)
          go build -o /tmp/ynab-exporter -ldflags "-X 'github.com/mcbobke/ynab-exporter/cmd/ynab-exporter/version.BuildTime=${BUILD_TIME}' -X 'github.com/mcbobke/ynab-exporter/cmd/ynab-exporter/version.BuildVersion=${BUILD_VERSION}'" ./cmd/ynab-exporter
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: ynab-exporter-binary
          path: /tmp/ynab-exporter

  release:
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout tag
        uses: actions/checkout@v2.4.0

      - name: Download artifact
        uses: actions/download-artifact@v2.1.0
        with:
          name: ynab-exporter-binary

      - name: Create release
        id: created_release
        uses:  ncipollo/release-action@v1.9.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          tag: ${{ github.ref }}
          name: ${{ github.ref }}
          draft: true
          prerelease: false
          artifacts: ./ynab-exporter
          artifactContentType: application/octet-stream
          generateReleaseNotes: true
