name: Branch - Build

on:
  push:
    branches-ignore: ['main']

jobs:
  build:
    name: Build and Upload Binary
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: [1.21.3]
      fail-fast: true
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4.1.0
      
      - name: Setup go ${{ matrix.go-version }}
        uses: actions/setup-go@v4.1.0
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Build ynab-exporter
        shell: bash
        run: go build -o /tmp/ynab-exporter -ldflags "-X 'github.com/mcbobke/ynab-exporter/cmd/ynab-exporter/version.BuildTime=$(date +%s)' -X 'github.com/mcbobke/ynab-exporter/cmd/ynab-exporter/version.BuildVersion=${GITHUB_REF_NAME}-$(date +%s)'" ./cmd/ynab-exporter
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ynab-exporter-binary
          path: /tmp/ynab-exporter