name: Docker Image CI - Main - Dated/Latest

on:
  push:
    branches-ignore: ['main']

jobs:
  build:
    name: Build and push Docker image for commit ${GITHUB_SHA}
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout main HEAD
      uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 0
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Build Docker image
      shell: bash
      run: >-
        docker build . --file Dockerfile
        --tag mcbobke/ynab-exporter:${GITHUB_SHA}-$(date +%s)
        --build-arg BUILD_VERSION=${GITHUB_SHA}-$(date +%s)
        --build-arg BUILD_TIME=$(date +%s)
    
    - name: Log in to Docker Hub
      shell: bash
      env:
        DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      run: echo ${DOCKERHUB_ACCESS_TOKEN} | docker login --username mcbobke --password-stdin
      
    - name: Push image (all tags)
      shell: bash
      run: docker push --all-tags mcbobke/ynab-exporter
