name: Docker Image CI - Main - Dated/Latest

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build, Tag and Push
    runs-on: ubuntu-20.04
    if: ${{ !contains(github.event.head_commit.message, '!skipci') && github.repository == 'mcbobke/ynab-exporter' }}
    steps:
    - name: Checkout main HEAD
      uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 0
        token: ${{ secrets.ACCESS_TOKEN }}

    # Will trigger the versioned release workflow
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        # Setting to false so that repo meta-commits don't create tags
        default_bump: false
        tag_prefix: v

    - name: Build Docker image
      shell: bash
      run: >-
        docker build . --file Dockerfile
        --tag mcbobke/ynab-exporter:$(date +%Y-%m-%d)
        --tag mcbobke/ynab-exporter:latest
        --build-arg BUILD_VERSION=${GITHUB_SHA}
        --build-arg BUILD_TIME=$(date +%s)
    
    - name: Log in to Docker Hub
      shell: bash
      env:
        DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      run: docker login --username mcbobke --password ${DOCKERHUB_ACCESS_TOKEN}
      
    - name: Push image (all tags)
      shell: bash
      run: docker push --all-tags mcbobke/ynab-exporter
