name: Docker Image CI - Main - Versioned

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    if: ${{ !contains(github.event.head_commit.message, '!skipci') && github.repository == 'mcbobke/ynab-exporter' }}
    steps:
    - uses: actions/checkout@v2.4.0

    - name: Build Docker image
      shell: bash
      run: >-
        docker build . --file Dockerfile
        --tag mcbobke/ynab-exporter:${GITHUB_REF_NAME}
        --build-arg BUILD_VERSION=${GITHUB_REF_NAME}
        --build-arg BUILD_TIME=$(date +%s)
    
    - name: Log in to Docker Hub
      shell: bash
      env:
        DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      run: docker login --username mcbobke --password ${DOCKERHUB_ACCESS_TOKEN}
      
    - name: Push image (all tags)
      shell: bash
      run: docker push --all-tags mcbobke/ynab-exporter
