name: Binary - Build/Release

on:
  push:
    tags: ['v*']

jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: [1.23.4]
      fail-fast: true
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4.2.2
      
      - name: Setup go ${{ matrix.go-version }}
        uses: actions/setup-go@v5.1.0
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Build ynab-exporter
        shell: bash
        run: go build -o /tmp/ynab-exporter -ldflags "-X 'github.com/mcbobke/ynab-exporter/cmd/ynab-exporter/version.BuildTime=$(date +%s)' -X 'github.com/mcbobke/ynab-exporter/cmd/ynab-exporter/version.BuildVersion=${GITHUB_REF_NAME}'" ./cmd/ynab-exporter
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ynab-exporter-binary
          path: /tmp/ynab-exporter

  release:
    name: Create Release
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4.2.2

      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: ynab-exporter-binary

      - name: Create release
        uses:  ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: true
          prerelease: false
          artifacts: ./ynab-exporter
          artifactContentType: application/octet-stream
          generateReleaseNotes: true
